"""
Package an exported .duf (+ its textures + fixup .dsa) into a DAZ Install
Manager (DIM) installable .zip - Tier 1 per the daz-dim-packaging skill
(Manifest.dsx + Supplement.dsx + Content/, no icon/category registration
needed for DIM to recognize and install it - live-confirmed end-to-end
against real DIM behavior 2026-08-12, see
AIHelpers/plugins/daz/skills/daz-dim-packaging/SKILL.md for the full schema
this follows).

Only concerned with repackaging what duf_export.py already produced - does
not touch DUF/DSON generation itself. The one real surgery this module does
is rewriting the in-memory duf dict's "image_file" fields from the absolute
local-disk paths duf_export writes (correct for loading straight from the
export folder, but meaningless once DIM installs the zip's contents to some
other Content Library path) to content-library-root-relative paths
("/Runtime/Textures/<Vendor>/<Product>/<file>") matching where this module
physically stages the same texture files under Content/Runtime/Textures/ -
and equivalently for the companion fixup script's bundled Iray Uber Base
preset path, which duf_export.py otherwise hardcodes as an absolute path to
this addon's own installed assets/ folder (only valid on the machine the
addon itself is installed on).
"""
import copy
import json
import os
import pathlib
import random
import shutil
import tempfile
import uuid
import zipfile

from . import duf_export


def _safe_folder(name):
    """Sanitize a vendor/product name for use as an on-disk folder segment
    and Manifest/Supplement display value - doesn't need to already be
    filesystem-safe going in (e.g. a raw Blender object name)."""
    keep = "".join(c if c.isalnum() or c in " _-" else "" for c in (name or "")).strip()
    return keep or "Untitled"


def _collect_and_rewrite_images(duf, dest_root_prefix):
    """Deep-copy `duf`, rewriting every "image_file" value from its current
    absolute source path to `<dest_root_prefix>/<basename>`.

    Returns (new_duf, {source_abs_path: dest_root_relative_path}) - the
    mapping drives the actual file copy in build_dim_package, kept separate
    here so this stays a pure data transform.
    """
    new_duf = copy.deepcopy(duf)
    copies = {}

    def walk(obj):
        if isinstance(obj, dict):
            for key, value in obj.items():
                if key == "image_file" and isinstance(value, str) and value:
                    basename = os.path.basename(value)
                    dest_rel = f"{dest_root_prefix}/{basename}"
                    copies[value] = dest_rel
                    obj[key] = dest_rel
                else:
                    walk(value)
        elif isinstance(obj, list):
            for item in obj:
                walk(item)

    walk(new_duf)
    return new_duf, copies


def _rewrite_fixup_preset_path(script_text, new_preset_path):
    """Swap the fixup script's embedded absolute local preset path for a
    content-library-root-relative one pointing at the copy this module
    stages under Content/Runtime/Support/ - see module docstring. The
    original is embedded via json.dumps() (see duf_export._js_str), so
    matching on that exact literal (rather than a looser path substring) is
    the reliable way to find and replace it regardless of OS path
    separators."""
    old_literal = json.dumps(duf_export._BUNDLED_UBER_BASE_PRESET)
    new_literal = json.dumps(new_preset_path)
    if old_literal not in script_text:
        raise ValueError(
            "Fixup script does not contain the expected bundled preset path literal - "
            "was it generated with a non-default preset_path?"
        )
    return script_text.replace(old_literal, new_literal)


def _manifest_dsx(content_root, global_id):
    """Per daz-dim-packaging skill Step 6 - one <File> entry per file that
    actually exists under Content/, generated by walking the staged
    directory rather than hand-listing."""
    lines = ['<DAZInstallManifest VERSION="0.1">', f' <GlobalID VALUE="{global_id}"/>']
    for f in sorted(content_root.rglob("*")):
        if f.is_file():
            rel = f.relative_to(content_root.parent).as_posix()
            lines.append(f' <File TARGET="Content" ACTION="Install" VALUE="{rel}"/>')
    lines.append("</DAZInstallManifest>")
    return "\n".join(lines)


def _supplement_dsx(product_name):
    """Per daz-dim-packaging skill Step 5 - live-confirmed this is where
    DIM's "Ready to Install" list gets its displayed Product Name/Tag from."""
    return (
        '<ProductSupplement VERSION="0.1">\n'
        f' <ProductName VALUE="{product_name}"/>\n'
        ' <InstallTypes VALUE="Content"/>\n'
        ' <ProductTags VALUE="DAZStudio4_5"/>\n'
        "</ProductSupplement>"
    )


def build_dim_package(duf, fixup_script_path, asset_basename, out_dir, product_name,
                       vendor_name="Blender Export", content_folder="Props"):
    """
    Package `duf` (the dict export_duf()/export_duf_prop() returned, still
    carrying its "_fixup_script" bookkeeping key - popped here, never
    written to disk) plus the companion fixup .dsa at fixup_script_path into
    a Tier 1 DIM-installable .zip written into out_dir.

    asset_basename is the .duf's filename without extension (pass the
    export operator's own chosen filename, not duf["asset_info"]["id"] -
    users may pick a different export filename than the mesh's Blender
    name).

    vendor_name/product_name become on-disk folder segments
    (Content/<content_folder>/<vendor>/<product>/...) and the Supplement.dsx
    display name - sanitized internally, don't need to already be
    filesystem-safe. content_folder is purely cosmetic (any string works for
    a Tier 1 install - see daz-dim-packaging skill); defaults to "Props" as
    a safe generic choice since this exporter has no reliable way to know
    the real Daz content-type taxonomy leaf for arbitrary Blender content.

    Returns the written zip's full path.
    """
    vendor = _safe_folder(vendor_name)
    product = _safe_folder(product_name)

    duf = dict(duf)
    duf.pop("_fixup_script", None)

    textures_prefix = f"Runtime/Textures/{vendor}/{product}"
    new_duf, image_copies = _collect_and_rewrite_images(duf, "/" + textures_prefix)

    with open(fixup_script_path, "r", encoding="utf-8") as f:
        fixup_text = f.read()
    support_prefix = "Runtime/Support/BlenderDUFExporter"
    new_preset_path = f"/{support_prefix}/IrayUberBase.duf"
    fixup_text = _rewrite_fixup_preset_path(fixup_text, new_preset_path)

    global_id = str(uuid.uuid4())
    product_num_id = random.randint(10000000, 99999999)
    zip_name = f"IM{product_num_id}-01_{product.replace(' ', '')}.zip"
    os.makedirs(out_dir, exist_ok=True)
    out_zip_path = os.path.join(out_dir, zip_name)

    stage_dir = tempfile.mkdtemp(prefix="daz_dim_stage_")
    try:
        content_root = pathlib.Path(stage_dir) / "Content"
        asset_dir = content_root / content_folder / vendor / product
        textures_dir = content_root / textures_prefix
        support_dir = content_root / support_prefix
        for d in (asset_dir, textures_dir, support_dir):
            d.mkdir(parents=True, exist_ok=True)

        with open(asset_dir / f"{asset_basename}.duf", "w", encoding="utf-8") as f:
            json.dump(new_duf, f, indent="\t")
        with open(asset_dir / os.path.basename(fixup_script_path), "w", encoding="utf-8") as f:
            f.write(fixup_text)
        for src, dest_rel in image_copies.items():
            if os.path.isfile(src):
                shutil.copy2(src, content_root / dest_rel.lstrip("/"))
        shutil.copy2(duf_export._BUNDLED_UBER_BASE_PRESET, support_dir / "IrayUberBase.duf")

        pathlib.Path(stage_dir, "Manifest.dsx").write_text(
            _manifest_dsx(content_root, global_id), encoding="utf-8")
        pathlib.Path(stage_dir, "Supplement.dsx").write_text(
            _supplement_dsx(product_name), encoding="utf-8")

        with zipfile.ZipFile(out_zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            stage_path = pathlib.Path(stage_dir)
            for f in sorted(stage_path.rglob("*")):
                if f.is_file():
                    zf.write(f, f.relative_to(stage_path).as_posix())
    finally:
        shutil.rmtree(stage_dir, ignore_errors=True)

    return out_zip_path
